import type { PredefinedMethod, AbiFunction } from '../../types';

const abi: AbiFunction[] = [
  // Seigniorage configuration functions
  {
    type: 'function',
    name: 'setData',
    inputs: [
      { name: 'powerton_', type: 'address' },
      { name: 'daoAddress', type: 'address' },
      { name: 'powerTONSeigRate_', type: 'uint256' },
      { name: 'daoSeigRate_', type: 'uint256' },
      { name: 'relativeSeigRate_', type: 'uint256' },
      { name: 'adjustDelay_', type: 'uint256' },
      { name: 'minimumAmount_', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setPowerTON',
    inputs: [{ name: 'powerton_', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setDao',
    inputs: [{ name: 'daoAddress', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setPowerTONSeigRate',
    inputs: [{ name: 'powerTONSeigRate_', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setDaoSeigRate',
    inputs: [{ name: 'daoSeigRate_', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setPseigRate',
    inputs: [{ name: 'pseigRate_', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setCoinageFactory',
    inputs: [{ name: 'factory_', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferCoinageOwnership',
    inputs: [
      { name: 'newSeigManager', type: 'address' },
      { name: 'coinages_', type: 'address[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceWTONMinter',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAdjustDelay',
    inputs: [{ name: 'adjustDelay_', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMinimumAmount',
    inputs: [{ name: 'minimumAmount_', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setSeigStartBlock',
    inputs: [{ name: '_seigStartBlock', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setInitialTotalSupply',
    inputs: [{ name: '_initialTotalSupply', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setBurntAmountAtDAO',
    inputs: [{ name: '_burntAmountAtDAO', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceMinter',
    inputs: [{ name: 'target', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renouncePauser',
    inputs: [{ name: 'target', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [{ name: 'target', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [
      { name: 'target', type: 'address' },
      { name: 'newOwner', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // Access control functions
  {
    type: 'function',
    name: 'addAdmin',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removeAdmin',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferAdmin',
    inputs: [{ name: 'newAdmin', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addMinter',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removeMinter',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addOperator',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removeOperator',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addChallenger',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removeChallenger',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
];

export const seigManagerMethods: PredefinedMethod = {
  id: 'tokamak-seig-manager',
  name: 'Tokamak SeigManager',
  description:
    'Tokamak Network SeigManager (V1.1) for seigniorage distribution management',
  abi,
  addresses: {
    mainnet: '0x0b55a0f463b6defb81c6063973763951712d0e5f',
    sepolia: '0x11F6f1C2c0800AC1b31F04fF8A9f5D9003a85460',
  },
};
